import Head from 'next/head'
import React from 'react'
import { AppProps } from 'next/app'
import '../styles/globals.css'
import '../components/ModalSolution/modal.scss';
import '../assets/style.scss'

const MyAppCustom: React.FC<AppProps> = ({ Component, pageProps }) => {
  return (
  <div className='root-app'>
    <Head>
        <title>Create Next App edit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='stylesheet' href="/css/global.css" />
    </Head>
    <Component {...pageProps} />
  </div>
  )
}

export default MyAppCustom
